<?php

declare(strict_types=1);

namespace Cfdi\Xsd;

final class SchemaKey
{
    public const TIPODATOS = 'CATALOGOS_TIPODATOS';

    public const CATALOGOS = 'CATALOGOS_CATALOGOS';

    public const COMPROBANTE = 'COMPROBANTE';

    public const INFORMACIONGLOBAL = 'COMPROBANTE_INFORMACIONGLOBAL';

    public const CFDIRELACIONADOS_CFDIRELACIONADO = 'COMPROBANTE_CFDIRELACIONADOS_CFDIRELACIONADO';

    public const CFDIRELACIONADOS = 'COMPROBANTE_CFDIRELACIONADOS';

    public const COMPROBANTE_EMISOR = 'COMPROBANTE_EMISOR';

    public const COMPROBANTE_RECEPTOR = 'COMPROBANTE_RECEPTOR';

    public const CONCEPTO_IMPUESTOS_TRASLADOS_TRASLADO = 'COMPROBANTE_CONCEPTOS_CONCEPTO_IMPUESTOS_TRASLADOS_TRASLADO';

    public const CONCEPTO_IMPUESTOS_RETENCIONES_RETENCION = 'COMPROBANTE_CONCEPTOS_CONCEPTO_IMPUESTOS_RETENCIONES_RETENCION';

    public const CONCEPTO_ACUENTATERCEROS = 'COMPROBANTE_CONCEPTOS_CONCEPTO_ACUENTATERCEROS';

    public const CONCEPTO_INFORMACIONADUANERA = 'COMPROBANTE_CONCEPTOS_CONCEPTO_INFORMACIONADUANERA';

    public const CONCEPTO_CUENTAPREDIAL = 'COMPROBANTE_CONCEPTOS_CONCEPTO_CUENTAPREDIAL';

    public const CONCEPTO_PARTE = 'COMPROBANTE_CONCEPTOS_CONCEPTO_PARTE';

    public const CONCEPTO = 'COMPROBANTE_CONCEPTOS_CONCEPTO';

    public const IMPUESTOS_RETENCIONES_RETENCION = 'COMPROBANTE_IMPUESTOS_RETENCIONES_RETENCION';

    public const IMPUESTOS_RETENCIONES = 'COMPROBANTE_IMPUESTOS_RETENCIONES';

    public const IMPUESTOS_TRASLADOS_TRASLADO = 'COMPROBANTE_IMPUESTOS_TRASLADOS_TRASLADO';

    public const IMPUESTOS_TRASLADOS = 'COMPROBANTE_IMPUESTOS_TRASLADOS';

    public const IMPUESTOS = 'COMPROBANTE_IMPUESTOS';

    public const IEDU = 'IEDU';
}
